replicaCount: 2

image:
  repository: 913704463047.dkr.ecr.eu-north-1.amazonaws.com/numbers-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
