apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: numbers-service
  template:
    metadata:
      labels:
        app: numbers-service
    spec:
      containers:
        - name: numbers-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
