apiVersion: v1
kind: Service
metadata:
  name: numbers-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: numbers-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
